source 'https://rubygems.org'

# RVM Directives for Gemset/Ruby specification
#ruby=2.2-head
#ruby-gemset=simply_pages

gem 'rails', '4.2.0'
gem 'sqlite3'

gem 'simply_pages', path: '../..'

# Use SCSS for stylesheets
gem 'sass-rails', '>= 5.0.2'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

group :development, :test do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
